import tv
def main():
    television = tv.TV()
    television.show_status()
    television.turn_on()
    television.show_status()
    television.volume_increase(5)
    television.show_channels()
    television.set_channels(["TVP1","TVP2","Polsat","TVN","Filmbox","Discovery","TVP3"])
    television.show_channels()
    television.set_channel(3)
    television.volume_increase(10)
    television.show_status()
    television.set_channel(1)
    television.volume_decrease(7)
    television.show_status()
    television.set_channel(6)
    television.show_status()
    television.set_channel(7)
    television.volume_decrease(2)
    television.show_status()
    television.set_channel(5)
    television.volume_decrease(7)
    television.show_status()    
    television.turn_off()
    television.show_status()

if __name__=="__main__":
    main()